### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [AlecksJohanssen/Android-Prework#1]
Hi Alecks Johanssen your submission is SUPER GREAT!.
/cc @coderschoolreview

**Comment by AlecksJohanssen** [comment]
Hello Coderschool this is aleckes! I loveyou! and thanks for reviewing my app!

**Comment by AlecksJohanssen** [comment]
Hello @coderschoolreview

**Comment by coderschoolreview** [comment]
123

**Comment by coderschoolreview** [comment]
123

**Comment by coderschoolreview** [comment]
123

**Comment by coderschoolreview** [comment]
123

**Comment by coderschoolreview** [comment]
Hi Alecks 
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
12333 
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
Test 
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
Hello

**Comment by AlecksJohanssen** [comment]
Hi 
/cc @coderschoolreview
